web/delivery/auth/urls.py
from django.urls import path

app_name = 'auth'

urlpatterns = [
    # Add your auth URL patterns here
]

web/delivery/orders/urls.py
from django.urls import path
from .views import OrdersListView

app_name = 'orders'

urlpatterns = [
    path("", OrdersListView.as_view(), name="orders_list")
]

web/delivery/restaurant/urls.py
from django.urls import path

app_name = 'restaurant'

urlpatterns = [
    # Add your restaurant URL patterns here
]

web/delivery/urls.py
from django.urls import path, include
from .views import HomeView

app_name = 'delivery'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path("orders/", include(("delivery.orders.urls", "orders"), namespace="orders"),),
    path("restaurant/", include(("delivery.restaurant.urls", "restaurant"), namespace="restaurant"),),
    path("auth/", include(("delivery.auth.urls", "auth"), namespace="auth"),),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('delivery.urls'))
]

web/delivery/actors/models.py
from django.db import models
from django.contrib.auth.models import User

class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=9)
    nif = models.CharField(max_length=9)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['updated_at']
    
    def __str__(self):
        return f'{self.nif} - {self.full_name()}'
    
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

web/delivery/orders/models.py
import uuid
from decimal import Decimal
from django.db import models

class Order(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    discount = models.DecimalField(max_digits=3, decimal_places=2)
    client_phone_number = models.CharField(max_length=9)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    @property
    def total_price(self) -> Decimal:
        result = 0
        
        # sum of all items prices in the order
        for item in self.items.all():
            result += item.price_after_tax
        
        # apply discount
        result = result - (result * self.discount)
        
        return result

    class Meta:
        ordering = ['updated_at']
    
    def __str__(self):
        return f"Order {self.uuid} - {self.total_price}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    name = models.CharField(max_length=255)
    quantity = models.IntegerField(default=1)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    iva_tax = models.DecimalField(max_digits=3, decimal_places=2, default=0.23)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    @property
    def price_befor_tax(self):
        return self.unit_price * self.quantity
    
    @property
    def price_after_tax(self):
        return self.price_befor_tax + (self.price_befor_tax * self.iva_tax)


    class Meta:
        ordering = ['updated_at']
    
    def __str__(self):
        return f"{self.name} - {self.unit_price} {self.quantity} x"

web/delivery/restaurant/models.py
from django.db import models

# Create your models here.

web/delivery/orders/views.py
from django.shortcuts import render
from django.views import View
from .models import Order

# Create your views here.
def home(request):
    context = {
        'title': 'Hello world'
        }
    return render(request, 'orders/index.html', context)

class OrdersListView(View):
    def get(self, request):
        
        orders = Order.objects.filter()
        
        context = {
            "orders": orders,
        }
        return render(request, "orders/list.html", context)

web/delivery/restaurant/views.py
from django.shortcuts import render

# Create your views here.

web/delivery/views.py
from django.shortcuts import render
from django.views import View

class HomeView(View):
    def get(self, request):
        localidades = 100
        restaurantes = 500
        estafetas = 1500
        distritos = 50

        context = {
            'title': 'O seu restaurante não precisa de estafetas. Agora tem o',
            'project_name': 'DeliveryLink',
            'localidades': localidades,
            'restaurantes': restaurantes,
            'estafetas': estafetas,
            'distritos': distritos
        }
        return render(request, 'delivery/index.html', context)

web/delivery/orders/templates/orders/index.html
{% extends 'base.html' %} {% block title %} Página Inicial {% endblock %} 
{% block content %}
<h1>Hello Hello from orders!</h1>
{% endblock %}

web/delivery/orders/templates/orders/list.html
{% extends "base.html" %}

{% block title %}orders{% endblock title %}

{% block content %}
  <div class="container mt-4">
    <h1>orders</h1>

    {% if orders %}
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">UUID</th>
            <th scope="col">Discount</th>
            <th scope="col">Client Phone Number</th>
            <th scope="col">Total Price</th>
            <th scope="col">Items Count</th>
          </tr>
        </thead>
        <tbody>
          {% for order in orders %}
            <tr>
              <td>{{ order.uuid }}</td>
              <td>{{ order.discount|floatformat:2 }} $</td>
              <td>{{ order.client_phone_number }}</td>
              <td>{{ order.total_price|floatformat:2 }}</td>
              <td>{{ order.items.count }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No orders available.</p>
    {% endif %}
  </div>
{% endblock content %}

web/delivery/templates/delivery/index.html
{% extends 'base.html' %} {% block title %} Página Inicial {% endblock %} 
{% block content %}
<h1>Hello World!</h1>
{% endblock %}

web/templates/base.html
{% load static %} {% load sass_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Delivery Link{% endblock %}</title>

    <link rel="stylesheet" href="{% sass_src 'custom.scss' %}" />
  </head>
  <body>
    {% include "partials/navbar.html" %}
    <main class="container py-4">{% block content %}{% endblock %}</main>
    {% include "partials/footer.html" %}

    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

web/templates/partials/footer.html
<footer class="py-3 mt-4 border-top text-center text-muted">
  <p>&copy; 2025 DeliveryLink</p>
</footer>

web/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="{% url 'delivery:home' %}">DeliveryLink</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" aria-current="page" href="{% url 'delivery:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'orders_list' %}active{% endif %}" href="{% url 'delivery:orders:orders_list' %}">Orders</a>
        </li>
      </ul>
    </div>
  </div>
</nav>